### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by DevbrosDevelopment** [Bekt/logspout-logstash#2]
I know, this is not a fault made by you, but maybe you can help me with that. Hopefully, because I'm stuck for hours! Thx 
```
logspout_1       | # logspout v3.2-dev-custom by gliderlabs
logspout_1       | # adapters: tcp logstash raw udp
logspout_1       | # options : persist:/mnt/routes
logspout_1       | # jobs    : http[]:80 pump routes
logspout_1       | # routes  :
logspout_1       | #   ADAPTER	ADDRESS		CONTAINERS	SOURCES	OPTIONS
logspout_1       | #   logstash	logstash:5000				map[]
logspout_1       | 2016/12/02 04:07:10 logstash: could not write:write udp 172.23.0.5:49301->172.23.0.4:5000: write: connection refused
elk2_logspout_1 exited with code 1
```
I am getting a connection refused, when the logspout-container is trying to connect to my logstash-container
docker-compose.yml
```
version: '2'
services:
  

  elasticsearch:
    build: elasticsearch/
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - docker_elk


  logstash:
    build: logstash/
    command: -f /etc/logstash/conf.d/
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "127.0.0.1:5000:5000/udp"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

  logspout:
    image: bekt/logspout-logstash
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ROUTE_URIS: logstash://logstash:5000
    networks:
      - docker_elk
    depends_on:
      - logstash
    

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - docker_elk
    depends_on:
      - elasticsearch

networks:
  docker_elk:
    driver: bridge
```
and my logstash.conf
```
input {
	tcp {
		port => 5000
		codec => json
	}
	udp {
		port => 5000
		codec => json
	}
}

## Add your filters / logstash plugins configuration here

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
}
```

**Comment by Bekt** [comment]
Hey there, if you're not using the tcp connection can you removing that from your logstash.conf?

Also you might try `ROUTE_URIS: logstash+udp://logstash:5000`.

**Comment by DevbrosDevelopment** [comment]
Thanks for your help and I think i found my error. Logspout was trying to connect to logstash but logstash wasn't accepting connections yet because it didn't start properly. I thought the `depends on` option ensures logspout is started after logstash, but it doesn't. Instead I'm using the `restart` option to accomplish logspout is started after logstash. Here's the edited part of my docker-compose.yml, maybe it helps someone. Btw I removed udp from .conf, left tcp in place and added tcp to REMOTE_URIS
```
logspout:
    image: bekt/logspout-logstash
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ROUTE_URIS: logstash+tcp://logstash:5000
    networks:
      - docker_elk
```
